### ISSUE TITLE
Failed import services

### ISSUE THREAD

**Issue by fsalazarsch** [jrperdomoz/khipu#1]
Luego de instalar correctamente, al arrancar el servicor aparece el error  

> File "/usr/local/lib/python2.7/dist-packages/khipu/__init__.py", line 4, in <module>
>     import services
> ImportError: No module named services
>

**Comment by ionatan-israel** [comment]
Que tal @fsalazarsch!  La verdad que hace mucho que empece este proyecto, nunca volví a utilizar khipu, así que no se si la api ha cambiado.  Sin embargo respecto a los problemas que mencionaste ya envíe un fix.  Saludos.
